# Generated by Django 5.1.3 on 2025-04-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('room', models.CharField(max_length=255, verbose_name='聊天室')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=20, null=True)),
                ('password', models.CharField(default=None, max_length=20, null=True)),
                ('manager', models.BooleanField(blank=True, default=False, null=True)),
                ('real_name', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
    ]
